src/errno.rs
src/fallocate.rs
src/lib.rs
src/poll.rs
src/seek_hole.rs
src/tempdir.rs
src/write_zeroes.rs

I only updated the documentation for the errno module by adding some more details to existing docs and  examples.
I also did a bit of cleanup in the way we are exporting functionality from this crate. The major change is having all functionality exported in public modules as oppose to export some of the functionality as bulk using `pub use mod_name::*`. This change also improves the readability of the documentation. Check it out with ```cargo doc --open```.

Small improvements to public documentation

---

src/seek_hole.rs

Seems that `clippy::cyclomatic_complexity` has been renamed to `clippy::cognitive_complexity`.
This tiny PR updates that in the code.

seek_hole: Fix clippy lint (cyclomatic_complexity)

---

coverage_config.json
src/lib.rs
src/rand.rs

Signed-off-by: Matt Forrester <github.com@speechmarks.com>
To implement the `tempfile` replacement I need the ability to generate random strings, thus random numbers also. This is taken from firecracker ( https://github.com/firecracker-microvm/firecracker/blob/master/fc_util/src/lib.rs ) as well as the alphanumeric stuff by myself.
I felt the need to add an author log for credits / possible issue tracking as we'll loose that across the repo's

rand: support getting random numbers and alphanumeric strings

---

coverage_config.json
src/fam.rs
src/lib.rs

In C an array of unknown size may appear within a struct definition
as the last member (as long as there is at least one other named member).
This is a known as flexible array member.
Pre C99, the same behavior could be achieved using zero length arrays.
Flexible Array Members are the go-to choice for working with large
amounts of data prefixed by header values.
KVM uses this type of structures (e.g., kvm_cpuid2, kvm_msr_list, etc.)
FamStructWrapper provides a common abstraction for this type of
structures and helps in treating them similarly to Rust Vec.
Signed-off-by: Serban Iorga <seriorga@amazon.com>

define wrapper for C FAM structs

---

coverage_config.json
src/timerfd.rs

clear(), FromRawFd and IntoRawFd are tested.
Fix #25.
Signed-off-by: Jing Liu <jing2.liu@linux.intel.com>

timerfd: Add unit tests

---

src/errno.rs
src/eventfd.rs
src/fallocate.rs
src/file_traits.rs
src/ioctl.rs
src/lib.rs
src/poll.rs
src/seek_hole.rs
src/signal.rs
src/syslog.rs
src/tempdir.rs
src/terminal.rs
src/timerfd.rs
src/write_zeroes.rs

The crate needs Apache-2.0 or BSD-3-Clause but some files are not correctly
described with the license. Make all files correct on license declaration.

license: improvements on license

---

coverage_config.json
src/fallocate.rs
src/file_traits.rs
src/seek_hole.rs
src/tempdir.rs
src/write_zeroes.rs

- added missing documentation
- refactored existing documentation examples so that we don't use functions
- the path field is now not optional anymore as there was no good reason for it to be optional

Tempdir Documentation & Refactoring

---

src/seek_hole.rs

Added high level documentation. Separated existing documentation into
summary and details.
This commit does not include examples for SeekHole trait because we
need a lot of boiler plate code to do that (we need to create a
temporary directory, create a file, write something to the file
and only then we are able to call into seek_data or seek_hole).

seek_hole: update documentation

---

coverage_config.json
src/lib.rs
src/tempfile.rs

This commit adds support for temporary files which will compliment the
existing temporary directory functionality.
Signed-off-by: Matt Forrester <github.com@speechmarks.com>

tempfile: add support for temporary files

---

src/errno.rs
src/lib.rs

Moved errno documentation from src/lib.rs to errno module.

errno: moved module documentation to module file

---

src/seek_hole.rs

They're only used in seek_hole.rs for the SeekHole implementation.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

seek_hole: No need to export SEEK_HOLE and SEEK_DATA

---

README.md
src/ioctl.rs
src/lib.rs

Added some more details to README.md and fixed the warnings generated by undocumented consts in ioctl.rs module.
This PR will fail the tests until #34 #31 are merged. It also depends on syslog being removed as that module doesn't have documentation for all public functions either.

High Level Documentation & ioctl documentation fixes

---

coverage_config.json
src/fam.rs

Implement From<Vec<T>> for FamStructWrapper, so we could move the Vec
instead of copy its content. Also implement trait From<&Vec<T>> for
convenience.
Signed-off-by: Jing Liu <jing2.liu@linux.intel.com>

Implement From<Vec<T>> for FamStructWrapper<T>

---

coverage_config.json
src/fam.rs

This rework `commit 27e7ff14d60de7ab22dbfbd46464798fa0714294 Implement From<Vec<T>> for FamStructWrapper<T>` with better abstraction.

Implement from/into_raw() for FamStructWrapper

---

CHANGELOG.md

I missed those when building the first version.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

CHANGELOG: Add the aio and sock_ctr_msg modules to the 0.1.0 release

---

CHANGELOG.md

Mostly for having a clean crates.io package license.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

CHANGELOG: v0.1.1 release

---

Cargo.toml

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

cargo: Bump version to 0.1.1

---

src/fam.rs

The macro that generates `impl FamStruct` for structs T with flexible array member now also takes a parameter to be able to specify the name of the flexible array member.
This is required as not all kernel structs having a flexible array member use the same field/member name for the respective member.

fam: macro to impl FamStruct also takes entries field name

---

CHANGELOG.md
Cargo.toml

Release an incremental version to include the new FAM functionality.

cargo: Bump version to 0.2.0

---

.gitignore
CHANGELOG.md
Cargo.toml
src/fam.rs

FamStructWrapper should not require `Clone` for the fam-struct `T` it safely wraps.
The underlying unsafe fam-struct type `T` cannot safely implement `Clone`. Attempting to reference the fam-member of such a clone can lead to UB.
We can still provide a safe `Clone` for the safe `FamStructWrapper`: instead of cloning the underlying `Vec<T>`, we can simply build a new `FamStructWrapper` using the safe builder starting from the original `[T::Entry]` where we know that `T::Entry` implements `Copy`.
Also bump the version to 0.2.1 to publish a fixed version.

fam: fix Clone for FamStructWrapper - bump version to include the fix

---

coverage_config.json
src/fallocate.rs
src/file_traits.rs
src/seek_hole.rs
src/tempdir.rs
src/tempfile.rs
src/write_zeroes.rs

Signed-off-by: Iulian Barbu <iul@amazon.com>
Implemented new methods for TempFile struct, respectively for TempDir struct:
- TempFile/TempDir::new() creates a new temp file inside $TMPDIR if set, otherwise inside /tmp.
- TempFile/TempDir::new_in(path) creates a new temp file inside an already existing valid path.
- TempFile/TempDir::new_with_prefix(prefix) is the old TempFile/TempDir::new(prefix) method.

tmpfile and tmpdir creation inside /tmp

---

CHANGELOG.md
coverage_config.json
src/rand.rs
src/signal.rs
src/timerfd.rs

Fixes #52 
Blocked all signals handlers execution when registering
a signal handler, for the registered signal handler.
Refactored SignalHandler enum to a SignalHandler type.
Signed-off-by: Iulian Barbu <iul@amazon.com>

Block signals handlers when registering a new signal handler

---

CHANGELOG.md
Cargo.toml

With the advent of the new methods from tempfile.rs and tempdir.rs, we should promptly support their usage through a new version of the crate.
Signed-off-by: Iulian Barbu <iul@amazon.com>

Bumped version to v0.3.0

---

src/signal.rs

Follow-up to #52. Now that the signals are absolute provide a way to obtain the base signal number. Also fix up some documentation changes that were missed in #52.

Expose real-time signal base

---

CHANGELOG.md
Cargo.toml

Exposing the function that provides the POSIX real time signal base
which is required to effectively use the signal API.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>

Bump version to 0.3.1

---

coverage_config.json
src/errno.rs

Referencing issue #58 , a basic implementation is proposed in this PR.
1. Implemented method `source` from `std::error::Error` for the custom error type `vmm_sys_util::errno::Error`.
2. Added unit test code for above implementation
Personally I think: Since the custom error type `pub struct Error(i32)` is just a wrapper of standard error, therefore there is no underlying error, hence we should always return `None` in the `source` method. Please do correct me if I am wrong. Thanks very much!
Signed-off-by: Henry Wang <<henry.wang@arm.com>>

Implement trait std::error::Error for vmm_sys_util::errno::Error

---

src/errno.rs

resolves https://github.com/rust-vmm/vmm-sys-util/pull/67#issuecomment-572535329
and
https://github.com/rust-vmm/vmm-sys-util/issues/58

src/errno.rs: remove bogus impl of std::error::Error::source()

---

src/tempfile.rs

Reimplement new_with_prefix() using rand::rand_alphanumerics() in order
to make it work on Windows.
Small fixes for the unit tests in order to run on Windows.
Signed-off-by: Serban Iorga <seriorga@amazon.com>

Make TempFile work on Windows

---

CHANGELOG.md
Cargo.toml

Updated changelog and version to 0.4.0.
We need to publish a new version so that we can get rid of the `tempfile` dependency in vm-memory.

release 0.4.0

---

CHANGELOG.md
Cargo.toml
src/fam.rs
src/lib.rs

#65
This PR makes `FamStructWrapper`s `serde`-serializable, provided that the wrapped data type is also `serde`-serializable.
The functionality is gated by the `with-serde` compilation feature.

fam wrappers: add conditional serde compatibility

---

src/errno.rs

Makes `err?` work in functions that return `io::Result<T>` :)

Implement Into<std::io::Error> for errno::Error

---

Cargo.toml
coverage_config.json
src/lib.rs
src/syscall.rs
src/unix/epoll.rs
src/unix/mod.rs

Added small wrapper over libc::epoll that can be used for the basic operations regarding the epoll
API.

Add epoll wrapper

---

coverage_config_aarch64.json
coverage_config_x86_64.json
src/unix/aio.rs
src/unix/epoll.rs

Some derives are useful (and needed by vmm-epoll).
Updated rust-vmm-ci as we were using  pretty old version.
Also fixed #84 because the build would fail otherwise.

Added some epoll derives & updated rust-vmm-ci

---

src/errno.rs

This will automatically give us blanket implementations of Into for io::Error and errno::Error. This simplifies things for client code that don't want to have to handle both errno::Error and io::Error and it's convenient because they don't have to explicitly convert between the types themselves.
For example, if an application programmer only wants to express failures from their code as io::Errors, then we don't have to go out of our way to map the result, we can still use the ? operator and the blanket trait conversions will still do the right thing:
```rust
use std::io;
struct ErrNo(i32);
impl From<io::Error> for ErrNo {
fn from(err: io::Error) -> ErrNo {
ErrNo(err.raw_os_error().unwrap())
}
}
impl From<ErrNo> for io::Error {
fn from(err: ErrNo) -> io::Error { …
```

Implement From<io::Error> for errno::Error

---

coverage_config_x86_64.json
src/lib.rs
src/metric.rs

The metric module adds astractions for working with metrics.
This module only defines the interface of metrics and it is not intended
for full implementations because each VMM should be able to define their
specific backend.
Merely this module defines an interface that can be used by other
rust-vmm components to define metrics in a generic way.

added metric module

---

src/unix/file_traits.rs

Resolves - https://github.com/rust-vmm/vmm-sys-util/issues/97
The file_traits module only contained test cases to test happy
paths. This commit adds a unit test to test a sad path for
the set_len method, which returns an error if the file was not
opened with the write option set to true.
Signed-off-by: Kshitij Jain <jkshtj@amazon.com>

Adds sad path unit tests for file_traits

---

.buildkite/pipeline.windows.yml

When we first added the Buildkite pipelines, there were some bugs in the
Buildkite docker plugin which did not allow us to use the upstream
version. We can now switch to upstream again.
Signed-off-by: Andreea Florescu <fandree@amazon.com>

CI: use upstream docker plugin

---

CHANGELOG.md
src/linux/epoll.rs

Add length check to Epoll::wait to prevent UB in safe code

---

src/linux/write_zeroes.rs

When fallocate fails in File's implementation of write_zeroes_at,
the fallback behavior is to write zeroes with write_at(); however,
this requires extending the filesize. Remove the assertion that
expects the filesize to remain the same -- otherwise tests will
spuriously fail on a system where fallocate returns -EOPNOTSUPP.
Signed-off-by: Connor Kuehl <ckuehl@redhat.com>

Don't assert that file size is unchanged for test_large_write_zeroes

---

coverage_config_x86_64.json
src/fam.rs

fix fam issues

---

coverage_config_x86_64.json
src/unix/tempdir.rs

I had TMPDIR set to /run/user/1000, and this made this test fail.
Signed-off-by: Alyssa Ross <hi@alyssa.is>

tempdir: fix test assuming that TMPDIR=/tmp

---

src/linux/sock_ctrl_msg.rs

Writes to arbitrary pointers are unsafe in Rust.  It's the caller's job to ensure that it's safe for the memory they are writing to can contain whatever arbitrary bytes are received over the socket.  For example, it would be unsafe to have an `iovec` pointing to the return value of `str::as_mut_ptr`, because strings can only contain byte sequences that are valid UTF-8.
Because it's on the caller to make sure they're passing pointers safely, any function that writes to `iovec`s has to be marked as unsafe.
Signed-off-by: Alyssa Ross <hi@alyssa.is>
***
Corresponding vhost change: https://github.com/rust-vmm/vhost/pull/69

sock_ctrl_msg: mark recv_with_fds as unsafe

---

coverage_config_x86_64.json
src/fam.rs
src/linux/eventfd.rs

The fam debug implementation is rather dummy, but it still helps with
debugging by allowing the derive on structures containing a fam struct.

derive Debug for fam & eventfd

---

coverage_config_x86_64.json
src/fam.rs
src/linux/poll.rs
src/linux/sock_ctrl_msg.rs
src/linux/timerfd.rs
src/unix/terminal.rs

This PR includes the original one from dependabot #156 
It fixes clippy warnings and test coverage due to updated Rust version.

Fix warnings and adjust test coverage

---

Cargo.toml

Fixes: https://github.com/rust-vmm/vm-memory/issues/199
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>

cargo: Use caret requirements for dependencies.

---

src/fam.rs

`vmm_sys_util::fam::Error` does not currently implement `std::error::Error`.
This introduces issues when attempting to write an error which contains this.
For example the below code is not possible without this trait implementation:
```rust
#[derive(Debug,thiserror::Error)]
pub enum MyError {
#[error("My error A {0:?}")]
A(#[from] vmm_sys_util::fam::Error),
// ...
}
```
requirements:
test.

Implementing `std::error::Error` for `fam::Error`

---

src/rand.rs

Signed-off-by: Vibha Acharya <vibharya@amazon.co.uk>
Under rand there is only one function to generate 'n' alphanumeric characters.
Generating 'n' random bytes is a useful and generic functionality.
Also corrected typo in existing function names.  
requirements:
test.

Added function to generate 'N' random bytes

---

CHANGELOG.md
src/rand.rs

Signed-off-by: Vibha Acharya <vibharya@amazon.co.uk>
rand_bytes() causes a panic when number of bytes requested are not multiples of 4.
`'main' panicked at 'attempt to subtract with overflow'`
Relates to : #178
The unit test was testing for 8 which is why it passed.
requirements:
test.

Fix panic caused by rand_bytes()

---

CHANGELOG.md
src/tempfile.rs

The name generation in `TempFile` is done by appending a randomly generated string of 6 alphanumeric characters to a prefix-path. This PR changes that implementation back ot using `mkstemp` on unix systems, to prevent name collisions. This additionally brings it inline with the `TempDir` implementation in the `unix::tempdir` module.
It seems that on windows something similar is possible via `GetTempFileName`, but I am too unfamiliar with the win32 api (and also have no windows machine available for testing) to be confident in implementing that change. 
We encountered spurious failures in tests due to multiple parallel running tests generating the same random file name. 
- Does this need a unit test?
- The (now windows-only) implementation of `TempDir::new_with_prefix` uses …

[TempFile] Revert to using `mkstemp` on unix

---

src/linux/seek_hole.rs
src/linux/write_zeroes.rs

Fix clippy issue from latest clippy about use of SeekFrom::Start(0)
rather than .rewind()
This allows rust-vmm-ci update.
requirements:
test.

linux: {seek_hole, write_zeroes}: Fix clippy issue

---

coverage_config_x86_64.json
src/lib.rs
src/linux/epoll.rs
src/linux/fallocate.rs
src/linux/poll.rs
src/linux/timerfd.rs
src/syscall.rs
src/tempfile.rs
src/unix/tempdir.rs

Sets `missing_debug_implementations` to deny and adds missing `std::fmt::Debug` implementations.
When tracing/logging/debugging a program it is common to debug print inputs and outputs of function, to do this generally dependencies need to offer `std::fmt::Debug` implementations.
I won't repeat what is written under [`missing_debug_implementations`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#missing-debug-implementations) which gives some more explanation.
requirements:
test.

fix: `missing_debug_implementations`

---

CHANGELOG.md
src/syscall.rs

Currently, `SyscallReturnCode` is limited to system call return values of type `i32`. However, not all system calls return 32-bit integer values. For example, the [`read` system call](https://man7.org/linux/man-pages/man2/read.2.html) returns an `ssize_t` type, which will map to a 64-bit integer on 64-bit systems.
This PR updates `SyscallReturnCode` to be a generic type that can contain any signed integer value, so it can be used with other integer types. Since existing code may not specify generic type values, I set the type parameter to default to the existing type of `c_int` to try and preserve compatibility.
requirements:
description …

Update SyscallReturnCode to support types other than i32.

---

CHANGELOG.md
Cargo.toml
src/lib.rs

The current documentation build in docs.rs does not include any crate features (at the moment just `with-serde`), which might lead to users of the crate not being aware of their existence.
requirements:
- `N/A` All added/changed functionality has a corresponding unit/integration
test.
- `N/A` Any newly added `unsafe` code is properly documented.

Build docs.rs documentation with features enabled

---

CHANGELOG.md

Update CHANGELOG with entry about the FamStructWrapper serde fix associated with GHSA: https://github.com/rust-vmm/vmm-sys-util/security/advisories/GHSA-875g-mfp6-g7f9
requirements:
test.

Prepare 0.12.0 release

---

CHANGELOG.md
Cargo.toml
src/fam.rs

We previously made as_mut_fam_struct() of FamStructWrapper private so
that we avoid that users modify the length of the header under our feet.
However, this disallows callers to modify other parts of the header
(which is totally safe to do).
Make as_mut_fam_struct() public again, but also mark it as unsafe,
asking users to guarantee that they will not change the length stored
within the header directly, via the mutable reference.
Also, prepare for release v0.12.1
requirements:
test.

Make `as_mut_fam_struct()` public and unsafe

---

CHANGELOG.md
src/linux/ioctl.rs

The `ioctl_io*_nr` macros expand to blocks that again contain macros. However, when doing this, the expanded code did not use `$crate`, meaning those submacros had to be in-scope at the call site. This could cause surpising compilation failures if macros were not imported, but rather referred to by their full name (e.g.
`vmm-sys-utils::ioctls::ioctl_iow_nr!`).
requirements:
test.

fix: make ioctl macro expand hygienically

---

CHANGELOG.md
src/fam.rs

Instead of re-interpreting the entire flexible array member contents as `T`, and then printing garbage, actually print out the FAM header, and then the _entries_ of the array.
Tightens the bound on the `Debug` implementation to require `T::Entry: Debug` (as opposed to just `T: Debug`).
requirements:
test.

Make `Debug` impl for `FamStructWrapper` print contents

---

CHANGELOG.md
src/fam.rs

The function was implemented exactly like the unsafe
`FamStructWrapper::from_raw`, without nothing preventing unsound usage
(e.g. passing in a Vec of length/capacity 1, but where the contained
element indicated a flexible array member of length > 0, which would
then later cause functions such as as_slice() to return a slice
referencing out-of-bounds memory).
Signed-off-by: Patrick Roy <roypat@amazon.co.uk>### Summary of the PR
requirements:
test.

fix: remove unsound impl From<Vec<T>> for FamStructWrapper<T>

---

src/fam.rs

Add a utility function for constructing an empty FamStructWrapper with a given header.
requirements:
test.

fam: add FamStructWrapper::from_header

---

.platform
README.md

This crate is a dependency of multiple other rust-vmm crates that already have riscv64 support enabled, so really we should be running riscv64 stuff in CI here too.
requirements:
test.

chore: enable riscv64 CI

---

CHANGELOG.md
src/fam.rs

Remove `PartialEq` trait constraint on `Entry`.
requirements:
test.

fam: Remove `PartialEq` trait constraint on `Entry`

---

CHANGELOG.md
Cargo.toml
src/linux/eventfd.rs
src/unix/event.rs
src/unix/mod.rs

Introduce an abstract event notification in order to support multiple platforms. EventNotifier is used to send a notification, and EventConsumer is used to receive a notification. The fd used in EventNotifier or EventConsumer can be from eventfd, pipefd or others.
They can be used like this: https://github.com/uran0sH/vhost/pull/1
requirements:
- [ x ] All commits in this PR have Signed-Off-By trailers (with
- [ x ] All added/changed functionality has a corresponding unit/integration
test.
- [ x ] All added/changed public-facing functionality has entries in the "Upcoming 
Release" section of …

Implement EventNotifier/EventConsumer as a generic event notification

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.toml

This release mainly improve support for macOS/BSD systems for vhost-user supporting sock_ctrl_msg on POSIX and adding a cross platform event notification that uses EventFd when available or pipe().
requirements:
test.

Prepare v0.15.0 release

---

CHANGELOG.md
src/linux/timerfd.rs

Currently, the timerfd module does not allow specifying different flags for the created timers. Add support for this via a new method, `TimerFd::new_with_flags`.
This will allow firecracker to use the implementation from this crate, instead of the dedicated `timerfd` crate (which pulls in the rustix crate, of which we have like 3 different versions in our dependency tree right now).
requirements:
test.

timerfd: support TFD_NONBLOCK flag
