rust-vmm/vmm-sys-util

- .buildkite/pipeline.yml
- .cargo/config
- src/signal.rs
> musl: adjust for incompatibility between standard library and libc

- src/eventfd.rs
Extend detailed documentation for eventfd module. 
Add examples for each public interface.
> eventfd improvements on documentation

- src/ioctl.rs
@andreeaflorescu @jiangliu @sameo 
Note: In ioctl.rs, there exists a set of definitions copied from kernel but no documentation, which needs more thinking.
> ioctl documentation improvement

- CODEOWNERS
- Cargo.toml
Please point to me if anything not correct.
> Add metadata and codeowners 

- src/fam.rs
Signed-off-by: Serban Iorga <seriorga@amazon.com>
> Fix fam module documentation

- coverage_config.json
- src/signal.rs
> signal: Add documentation and unit test

- Cargo.toml
- src/poll.rs
- src/rand.rs
* clippy warning fixes
* `Cargo.toml` license
> Post release fixes

- src/signal.rs
Blocked restricted signals from signal handling as like mentioned in [http://man7.org/linux/man-pages/man2/sigaction.2.html](url)
Signed-off-by: karthik nedunchezhiyan <karthik1705.n@gmail.com>
> signal: Block restricted signals in signal handler

- src/tempfile.rs
This method consumes the TempFile returning the wrapped file.
It also removes the file from the system. The file descriptor remains
opened and it can be used until the returned file is dropped.
Adding this method enables us to [drop the dependency on the tempfile crate
in favor of vmm-sys-util inside vm-memory](https://github.com/rust-vmm/vm-memory/issues/23). This helps us to remove about
17 sub-dependencies.
Signed-off-by: Serban Iorga <seriorga@amazon.com>
> [TempFile] add into_file() method

- CHANGELOG.md
- Cargo.toml
> release v0.6.1

- Cargo.toml
- src/errno.rs
- src/fam.rs
- src/lib.rs
- src/linux/epoll.rs
- src/linux/ioctl.rs
- src/linux/poll.rs
- src/linux/signal.rs
- src/rand.rs
> switch to Rust 2018

- src/fam.rs
- src/linux/ioctl.rs
- src/linux/signal.rs
- src/unix/tempdir.rs
0fc8ced refactor test_benchmark.py
741b894 checkout to PR branch before finishing test_bench
645a5c3 test_bench: don't crash when no bench on master
bd32544 Fetch origin in benchmark test
35beb91 Fix commit message test
53427aa benchmarks: add test that can run at every PR
abd2c90 Add test for commit message format
fe859f4 Update container image to v6
75d7254 run cargo check on all features
Signed-off-by: Andreea Florescu <fandree@amazon.com>
> updated rust-vmm-ci

- src/unix/tempdir.rs
Signed-off-by: u5surf <u5.horie@gmail.com>
Fixes #101 
Adding unit tests which remove a directory that contains other directories
> Add unit tests remove a directory that contains other directories #101

- coverage_config_x86_64.json
- src/metric.rs
- src/tempfile.rs
> doc and tests improvement

- CHANGELOG.md
- coverage_config_x86_64.json
- src/linux/write_zeroes.rs
#109 
More details in the commit message.
> use FALLOC_FL_ZERO_RANGE for write_zeroes

- CHANGELOG.md
- coverage_config_x86_64.json
- src/linux/poll.rs
enhance linux/poll.rs by
1) add more utility methods to PollEvent
2) derive(Copy, Clone) for PollWatchingEvent
> Add more utility methods to linux/poll

- CHANGELOG.md
- Cargo.toml
Releases the newest version of vmm-sys-util.
> release v0.8.0

- coverage_config_x86_64.json
- src/linux/epoll.rs
- src/linux/sock_ctrl_msg.rs
- src/linux/timerfd.rs
There are ocurrences of unsafe blocks that do not have comments regarding why the operations are safe.
Added comments for why the unsafe blocks are safe and logic to back up the safety assurance.
> Unsafe blocks safety

- CHANGELOG.md
- Cargo.toml
There are some interface changes, so bump the minor version.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
Fixes: #124
> Prepare for releasing v0.9.0

- Cargo.toml
- src/lib.rs
- src/linux/epoll.rs
- src/linux/ioctl.rs
- src/linux/seek_hole.rs
Adds some cfgs for target_os=android so firecracker works on Android hosts (https://github.com/firecracker-microvm/firecracker/issues/3008#issuecomment-1142183086)
requirements:
**Hey, shouldn't it be -S?**
test.
> adds android support

- src/linux/ioctl.rs
Using a const fn for `ioctl_expr` instead of a declarative macro.
When possible it is always better to use a const fn over a macro. They offer better code readability, better documentation and stronger typing offering better safety.
requirements:
test.
> `ioctl_expr` const fn

- src/fam.rs
- src/linux/signal.rs
```
Update rust-vmm-ci to v16
258161e update README with latest version
6fbd7c7 fix test commit format
b3ed1c9 update to container version 16
Signed-off-by: nikson <nikson@users.noreply.github.com>
```
Updated rust-vmm-ci sub-module to latest version (v16)
requirements:
test.
> Update rust-vmm-ci to v16

- Cargo.toml
Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Upgrade to 2021 edition
requirements:
test.
> Upgrade to 2021 edition

- src/rand.rs
The function was written as C-style. Use iterators and combinators.
requirements:
test.
> rustify the `xor_pseudo_rng_u8_alphanumerics` function

- CHANGELOG.md
- Cargo.toml
Details in CHANGELOG.md.
A few notes on this release:
- this release is important because it releases the work of specifying dependencies as caret, which should reduce the risk of breaking customer code.
- in the changelog, I only added links to the issues where they were specified in the commit message. Getting the links for all the PRs is pretty heavy weighted for a release and it just making us delay releases when releases are due. Instead we should check the commit messages during the review/find a way to automate the checks or the release.
requirements:
test.
> release v0.11.0

- CHANGELOG.md
- Cargo.toml
Prepared a 0.11.2 release so that users can consume the changes of #201 (note that this is a backward compatible change according to https://doc.rust-lang.org/cargo/reference/semver.html#generic-new-default)
requirements:
test.
> Prepare 0.11.2 release

- src/fam.rs
Add some additional checks around integer overflows when multiplying/casting, to ensure that code added in the future does not trigger potential overflow bugs.
requirements:
test.
> Harden FamStructWrapper against integer overflows

- src/tempfile.rs
If an error is returned after calling `CString::into_raw` and before calling `CString::from_raw` the memory allocated for the string is leaked. This could previously occur within `TempFile::new_with_prefix`.
requirements:
test.
> Fix possible memory leak

- src/fam.rs
> fam: fix typo in documentation

- src/errno.rs
While trying to enable the unit tests in Android (see https://r.android.com/3044134), I noticed test failures saying:
thread 'errno::tests::test_errno' panicked at
external/rust/crates/vmm-sys-util/src/errno.rs:156:14:
called `Result::unwrap()` on an `Err` value: Os { code: 21, kind:
IsADirectory, message: "Is a directory" }
I believe this is because of the hard-coded name for the temporary file in the `test_errno` unit test.
Using a randomized temp directory should fix this.
requirements:
test.
> fix: use random temporary directory in test

- CHANGELOG.md
- Cargo.toml
Release with `align` module.
requirements:
test.
> chore: Prepare 0.13.0 release

- CHANGELOG.md
- Cargo.toml
> chore: Prepare 0.14.0 release
